### PR TITLE
Add plugins to included configs

### PR DESCRIPTION
**Pull request by mjchang**
add `redux-saga` plugin to the included `recommended` and `all` configs so user doesn't have to define the plugin themselves

### CODE REVIEW

**Comment by pke** [comment]
Thanks for your caring by creating this PR. An easy merge ;)

**Comment by mjchang** [comment]
@pke Thanks for the quick merge. Is 1.2.1 released? Not seeing it on npm.

**Comment by pke** [comment]
Not sure why my travis deploy step still does not work. Released manually just now.

**Comment by mjchang** [comment]
Thanks! See it now.

**Pull request merged**
