### PR TITLE
Add hasSuggestions meta to yield-effects rule

### LINKED ISSUE #79: Provide support for eslint 8
Would be great to have this package support eslint 8.

### PR DESCRIPTION
**Pull request by rosczja**
Fixes  pke/eslint-plugin-redux-saga#79

### CODE REVIEW

**Comment by dbasilio** [comment]
Can this get merged in and released 🙏 it's blocking us from upgrading to eslint 8

**Comment by pke** [comment]
Released as 1.2.2

**Comment by dbasilio** [comment]
Thanks so much! 🙏

**Comment by rosczja** [comment]
Thank you 👍

**Pull request merged**
