### PR TITLE
Account for `takeLeading` as a non-catchable effect

### PR DESCRIPTION
**Pull request by fuller**
https://github.com/redux-saga/redux-saga/tree/master/docs/api#takeleadingpattern-saga-args

### CODE REVIEW

**Comment by pke** [comment]
Thanks for your (first) contribution to this repo. 
Would you be able to add some tests for this new side-effect?

**Comment by ajfuller** [comment]
For sure I’ll try to get to that tomorrow

**Comment by ajfuller** [comment]
@pke added test with https://github.com/pke/eslint-plugin-redux-saga/pull/63/commits/f2e4803a424b28d4b5efcb0f6f346bf2b5d5bc19

**Comment by pke** [comment]
Fixes #64, thanks!

**Pull request merged**
